import React, { useEffect, useState } from 'react';
import type { User } from 'firebase/auth';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { finishGoogleRedirect, login, loginWithGoogle, logout, register, subscribeToAuth } from '../auth';

const resizePhoto = (file: File): Promise<string> => new Promise((resolve, reject) => {
  const reader = new FileReader(); reader.onerror = reject; reader.onload = () => { const img = new Image(); img.onload = () => { const size=320, scale=Math.min(size/img.width,size/img.height,1), canvas=document.createElement('canvas'); canvas.width=Math.max(1,Math.round(img.width*scale)); canvas.height=Math.max(1,Math.round(img.height*scale)); const ctx=canvas.getContext('2d'); if(!ctx)return reject(new Error('Не вдалося обробити фото.')); ctx.drawImage(img,0,0,canvas.width,canvas.height); resolve(canvas.toDataURL('image/jpeg',0.78)); }; img.onerror=reject; img.src=String(reader.result); }; reader.readAsDataURL(file); });

export const AuthPanel: React.FC = () => {
 const [user,setUser]=useState<User|null>(null),[nickname,setNickname]=useState(''),[savedNickname,setSavedNickname]=useState(''),[photo,setPhoto]=useState(''),[mode,setMode]=useState<'login'|'register'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const unsub=subscribeToAuth(async u=>{setUser(u); if(!u){setSavedNickname('');setNickname('');setPhoto('');return;} try{const p=await getDoc(doc(db,'users',u.uid));const d=p.exists()?p.data():{};const n=String(d.nickname||'');setSavedNickname(n);setNickname(n||u.displayName||'');setPhoto(String(d.photo||u.photoURL||''));}catch(e:any){setError(`Профіль: ${e?.code||'error'} — ${e?.message||'не вдалося завантажити'}`);}}); finishGoogleRedirect().catch((e:any)=>{if(e?.code&&e.code!=='auth/no-auth-event')setError(`Google: ${e.code} — ${e.message||'помилка авторизації'}`);}); return unsub;},[]);
 const saveProfile=async()=>{if(!user)return;const n=nickname.trim();if(n.length<2||n.length>40){setError('Імʼя має містити від 2 до 40 символів.');return;}setBusy(true);setError('');setNotice('');try{await setDoc(doc(db,'users',user.uid),{nickname:n,email:user.email||'',photo:photo||'',updatedAt:new Date().toISOString()},{merge:true});setSavedNickname(n);setNotice('✅ Профіль збережено');}catch(e:any){setError(`Профіль: ${e?.code||'error'} — ${e?.message||'не вдалося зберегти'}`);}finally{setBusy(false);}};
 const choosePhoto=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/')){setError('Оберіть зображення.');return;}if(f.size>8*1024*1024){setError('Фото має бути до 8 МБ.');return;}setError('');setNotice('');setBusy(true);try{setPhoto(await resizePhoto(f));}catch{setError('Не вдалося обробити фото.');}finally{setBusy(false);e.target.value='';}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setNotice('');setBusy(true);try{if(mode==='login')await login(email,password);else await register(email,password);setEmail('');setPassword('');}catch(e:any){setError(`Email: ${e?.code||'error'} — ${e?.message||'помилка'}`);}finally{setBusy(false);}};
 const googleSignIn=async()=>{setError('');setNotice('');setBusy(true);try{await loginWithGoogle();}catch(e:any){setBusy(false);setError(`Google: ${e?.code||'error'} — ${e?.message||'помилка авторизації'}`);}};
 if(user)return <div className="bg-slate-900/95 p-5 rounded-3xl border border-cyan-900/50 space-y-4 shadow-2xl"><div className="text-center"><div className="mx-auto relative h-24 w-24 overflow-hidden rounded-full border-4 border-cyan-300/70 bg-slate-800 shadow-xl">{photo?<img src={photo} alt="Фото профілю" className="h-full w-full object-cover"/>:<div className="h-full w-full flex items-center justify-center"><span className="text-3xl">👤</span></div>}</div><label className="mt-3 inline-flex cursor-pointer items-center justify-center rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-xs font-extrabold text-cyan-200">📷 Додати фото<input type="file" accept="image/*" onChange={choosePhoto} className="hidden"/></label></div><div><div className="text-sm font-extrabold text-white">👤 Мій акаунт</div><div className="mt-1 text-[11px] text-purple-300/70 break-all">Google: {user.email||'без email'}</div></div><div><label className="block text-xs font-bold text-slate-200 mb-1.5">Імʼя профілю</label><input value={nickname} onChange={e=>{setNickname(e.target.value);setNotice('');}} maxLength={40} placeholder="Наприклад: Назар" className="w-full px-3.5 py-3 rounded-xl bg-slate-950 border border-purple-900/50 text-white text-xs outline-none focus:border-cyan-400"/></div><button type="button" disabled={busy} onClick={saveProfile} className="!block w-full min-h-[52px] py-3 bg-gradient-to-r from-cyan-500 to-indigo-600 disabled:opacity-50 text-white font-extrabold text-sm rounded-xl shadow-lg">{busy?'Зберігаємо…':'💾 ЗБЕРЕГТИ ПРОФІЛЬ'}</button>{notice&&<div className="rounded-xl bg-emerald-500/15 border border-emerald-400/30 p-3 text-center text-sm font-bold text-emerald-300">{notice}</div>}{error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200 break-words">{error}</div>}<div className="text-xs text-cyan-300 text-center">Профіль: {savedNickname||'імʼя ще не задане'}</div><button type="button" onClick={()=>logout()} className="w-full py-2.5 bg-slate-800 text-white font-extrabold text-xs rounded-xl">Вийти</button></div>;
 return <div className="bg-slate-900/95 p-5 rounded-3xl border border-cyan-900/50 space-y-3 shadow-2xl"><div className="text-sm font-extrabold text-white">👤 Увійти в акаунт</div><p className="text-xs text-purple-200/70">Увійдіть через Google або Email.</p><button type="button" disabled={busy} onClick={googleSignIn} className="w-full py-3 bg-white disabled:opacity-50 text-slate-900 font-extrabold text-xs rounded-xl">G&nbsp;&nbsp;{busy?'Переходимо до Google…':'Увійти через Google'}</button><div className="flex items-center gap-2 text-[10px] text-slate-500"><span className="h-px flex-1 bg-slate-700"/><span>АБО EMAIL</span><span className="h-px flex-1 bg-slate-700"/></div><form onSubmit={submit} className="space-y-2.5"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="Email" className="w-full px-3.5 py-2.5 rounded-xl bg-slate-950 border border-purple-900/50 text-white text-xs outline-none"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={6} placeholder="Пароль (мінімум 6 символів)" className="w-full px-3.5 py-2.5 rounded-xl bg-slate-950 border border-purple-900/50 text-white text-xs outline-none"/>{error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200 break-words">{error}</div>}<button disabled={busy} type="submit" className="w-full py-2.5 bg-purple-600 disabled:opacity-50 text-white font-extrabold text-xs rounded-xl">{busy?'Зачекайте…':mode==='login'?'Увійти':'Створити акаунт'}</button></form><button type="button" onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}} className="text-xs text-cyan-300 underline">{mode==='login'?'Створити новий акаунт':'У мене вже є акаунт'}</button></div>;
};