import React, { useEffect, useRef, useState } from 'react';
import { X, CheckCircle2, AlertCircle, Send, MapPin, LocateFixed, Loader2, Camera, ImagePlus } from 'lucide-react';
import { CategoryId, CATEGORIES, UrgencyLevel, UrgentHelpType, URGENCY_LEVELS_MAP, URGENT_TYPES_MAP, Listing, PayType } from '../types';
import { ListingMapPicker } from './ListingMapPicker';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { storage } from '../firebase';

interface CreateListingModalProps { isOpen:boolean; onClose:()=>void; onSubmit:(newListing:Omit<Listing,'id'|'createdAt'|'viewsCount'|'callsCount'|'distanceMeters'>)=>Promise<boolean>; userCoordinates?:[number,number]; gpsEnabled?:boolean; }
const MAIN_CATEGORY_IDS: CategoryId[] = ['service','rideshare','sale','buy','rent','giveaway','other','urgent'];
const SALE_SUBCATEGORIES = ['Телефони та електроніка','Нерухомість','Автомобілі','Запчастини','Для дому','Інструменти','Одяг та взуття','Дитячі товари','Сад та город','Тварини','Сільське господарство','Продукти харчування','Інше'];

export const CreateListingModal:React.FC<CreateListingModalProps>=({isOpen,onClose,onSubmit,userCoordinates,gpsEnabled=false})=>{
 const [category,setCategory]=useState<CategoryId>('service'); const [subcategory,setSubcategory]=useState(''); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [payAmount,setPayAmount]=useState(''); const [payType,setPayType]=useState<PayType>('fixed'); const [locationName,setLocationName]=useState(''); const [when,setWhen]=useState('Сьогодні'); const [duration,setDuration]=useState('2 години'); const [phone,setPhone]=useState(''); const [photoUrl,setPhotoUrl]=useState(''); const [photoFile,setPhotoFile]=useState<File|null>(null); const [photoPreview,setPhotoPreview]=useState(''); const [urgencyLevel,setUrgencyLevel]=useState<UrgencyLevel>('immediate'); const [urgentType,setUrgentType]=useState<UrgentHelpType>('auto'); const [mapOpen,setMapOpen]=useState(false); const [coordinates,setCoordinates]=useState<[number,number]|null>(null); const [locating,setLocating]=useState(false); const [uploadingPhoto,setUploadingPhoto]=useState(false); const [success,setSuccess]=useState(false); const [errorMessage,setErrorMessage]=useState(''); const [busy,setBusy]=useState(false); const photoInputRef=useRef<HTMLInputElement|null>(null);
 const isUrgent=category==='urgent'; const currentCategory=CATEGORIES[category]; const subcategories=category==='sale'?SALE_SUBCATEGORIES:(currentCategory?.subcategories??[]); const selectedCoordinates=coordinates||(gpsEnabled&&userCoordinates?userCoordinates:null); const canPublish=Boolean(selectedCoordinates);
 useEffect(()=>{if(!isOpen)return; setSuccess(false);setErrorMessage('');setBusy(false);setMapOpen(false);setCoordinates(null);setLocationName('');setPhotoUrl('');setPhotoFile(null);setPhotoPreview('')},[isOpen]);
 useEffect(()=>()=>{if(photoPreview)URL.revokeObjectURL(photoPreview)},[photoPreview]);
 const handlePhoto=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){setErrorMessage('Оберіть саме фото.');return}if(file.size>10*1024*1024){setErrorMessage('Фото завелике. Максимум 10 МБ.');return}if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoFile(file);setPhotoPreview(URL.createObjectURL(file));setPhotoUrl('');setErrorMessage('')};
 const uploadPhoto=async()=>{if(!photoFile)return '';setUploadingPhoto(true);try{const safeName=photoFile.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`listings/${Date.now()}_${Math.random().toString(36).slice(2)}_${safeName}`;const storageRef=ref(storage,path);const snapshot=await uploadBytes(storageRef,photoFile,{contentType:photoFile.type});return await getDownloadURL(snapshot.ref)}finally{setUploadingPhoto(false)}};
 const determineAutomatically=()=>{if(!navigator.geolocation){setErrorMessage('Цей браузер не підтримує визначення місцезнаходження.');return}setLocating(true);setErrorMessage('');navigator.geolocation.getCurrentPosition(p=>{const c:[number,number]=[p.coords.latitude,p.coords.longitude];setCoordinates(c);setLocating(false);setMapOpen(true)},e=>{setLocating(false);setErrorMessage(e.code===1?'Дозвольте браузеру доступ до геолокації та натисніть кнопку ще раз.':'Не вдалося визначити місцезнаходження. Перевірте GPS.')},{enableHighAccuracy:true,timeout:12000,maximumAge:0})};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setErrorMessage('');if(!canPublish){setErrorMessage('📍 Спочатку визначте місце автоматично або виберіть точку на карті.');return}if(!title.trim()){setErrorMessage('Вкажіть заголовок оголошення.');return}if(!phone.trim()){setErrorMessage('Вкажіть номер телефону.');return}let pay=payAmount?`${payAmount} грн`:'За домовленістю';if(payType==='hourly')pay+='/год';if(payType==='daily')pay+='/день';if(payType==='monthly')pay+='/міс';if(payType==='free')pay='Безкоштовно';setBusy(true);try{const uploadedUrl=photoFile?await uploadPhoto():photoUrl;const ok=await onSubmit({title:isUrgent?`🚨 ${title}`:title,category,subcategory:subcategory||undefined,description:description||'Опис не вказано.',pay,payValueNumber:parseInt(payAmount.replace(/\D/g,''),10)||0,payType,locationName:locationName.trim(),coordinates:selectedCoordinates!,when:isUrgent?'Терміново (зараз)':when,duration,phone,isUrgent,urgencyLevel:isUrgent?urgencyLevel:undefined,urgentType:isUrgent?urgentType:undefined,photoUrl:uploadedUrl||undefined,verified:true});if(ok)setSuccess(true);else setErrorMessage('Не вдалося опублікувати. Спочатку увійдіть в акаунт.')}catch(error){console.error(error);setErrorMessage('Не вдалося завантажити фото або опублікувати оголошення. Перевірте Firebase Storage.')}finally{setBusy(false)}};
 if(!isOpen)return null;
 return <>
  <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md overflow-y-auto overscroll-contain" style={{WebkitOverflowScrolling:'touch'}}>
   <div className="min-h-full flex items-start sm:items-center justify-center p-2 sm:p-3">
    <div className="relative w-full max-w-xl bg-slate-950/95 text-slate-100 rounded-3xl shadow-2xl border border-purple-900/50 overflow-hidden my-2 sm:my-6 flex flex-col max-h-none sm:max-h-[92vh]">
     <div className="shrink-0 p-4 border-b border-purple-900/40 flex items-center justify-between"><div><h2 className="text-lg font-black">Додати оголошення</h2><p className="text-[11px] text-purple-300/70">Оберіть категорію та підкатегорію</p></div><button type="button" onClick={onClose} className="w-9 h-9 rounded-full bg-slate-900 text-purple-300 border border-purple-800/40 flex items-center justify-center"><X className="w-5 h-5"/></button></div>
     <div className="p-4 sm:p-6 space-y-4 pb-8">
      {success ? <div className="py-8 text-center space-y-4"><CheckCircle2 className="w-16 h-16 mx-auto text-emerald-400"/><h3 className="text-xl font-black">Оголошення опубліковано!</h3><button type="button" onClick={onClose} className="px-8 py-3 bg-purple-600 rounded-2xl font-extrabold">Готово</button></div> : <form onSubmit={submit} className="space-y-4">
       <div className={`p-3 rounded-2xl border text-xs font-bold flex gap-2 ${canPublish?'bg-emerald-950/50 text-emerald-200 border-emerald-800/60':'bg-amber-950/60 text-amber-200 border-amber-800/60'}`}><MapPin className="w-4 h-4 shrink-0"/><span>{canPublish?'Місце визначено. Координати збережено.':'Визначте місце для оголошення.'}</span></div>
       <div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><button type="button" onClick={determineAutomatically} disabled={locating} className="py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-60 text-white font-black flex items-center justify-center gap-2"><LocateFixed className="w-4 h-4"/>{locating?<><Loader2 className="w-4 h-4 animate-spin"/>Визначаю...</>:'Визначити автоматично'}</button><button type="button" onClick={()=>{setErrorMessage('');setMapOpen(true)}} className="py-3 rounded-2xl bg-cyan-600 hover:bg-cyan-500 text-white font-black flex items-center justify-center gap-2"><MapPin className="w-4 h-4"/>Вказати місце на карті</button></div>
       {coordinates&&<div className="p-3 rounded-2xl bg-emerald-950/50 border border-emerald-800/50 text-xs font-bold text-emerald-200">📍 Координати вибрані: {coordinates[0].toFixed(6)}, {coordinates[1].toFixed(6)}</div>}
       {errorMessage&&<div className="p-3 bg-rose-950/80 text-rose-200 border border-rose-800/60 rounded-2xl text-xs font-bold flex gap-2"><AlertCircle className="w-4 h-4"/>{errorMessage}</div>}
       <div><label className="text-xs font-extrabold text-purple-300">ОСНОВНА КАТЕГОРІЯ</label><div className="flex gap-2 overflow-x-auto mt-2 pb-1">{MAIN_CATEGORY_IDS.map(k=><button key={k} type="button" onClick={()=>{setCategory(k);setSubcategory('')}} className={`shrink-0 px-3 py-2 rounded-2xl text-left border ${category===k?'bg-purple-600 text-white border-purple-400':'bg-slate-900 text-purple-200 border-purple-900/40'}`}><span>{CATEGORIES[k].pinSymbol}</span><span className="block text-xs font-extrabold mt-1">{CATEGORIES[k].shortLabel}</span></button>)}</div></div>
       {subcategories.length>0 && <div><label className="text-xs font-extrabold text-cyan-300">ПІДКАТЕГОРІЯ {category==='sale'?'— ПРОДАМ':''}</label><div className="flex flex-wrap gap-1.5 mt-2">{subcategories.map(s=><button key={s} type="button" onClick={()=>setSubcategory(subcategory===s?'':s)} className={`px-3 py-1.5 rounded-xl text-xs font-bold border ${subcategory===s?'bg-cyan-500 text-slate-950':'bg-slate-950 text-purple-200 border-purple-800/40'}`}>{s}</button>)}</div></div>}
       <input required value={title} onChange={e=>setTitle(e.target.value)} placeholder={isUrgent?'Що потрібно терміново?':'Назва оголошення'} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/>
       <textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Опис та деталі" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/>
       <input value={locationName} onChange={e=>setLocationName(e.target.value)} placeholder="Вулиця, номер або назва місця" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/>
       <input value={phone} onChange={e=>setPhone(e.target.value)} required type="tel" placeholder="+380..." className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/>
       <div><label className="text-xs font-extrabold text-cyan-300">ФОТО ТОВАРУ — 1 ФОТО</label><div className="mt-2 rounded-2xl border border-dashed border-cyan-500/50 bg-slate-900/70 p-3">{photoPreview?<div className="relative"><img src={photoPreview} alt="Фото товару" className="w-full max-h-64 object-contain rounded-xl bg-slate-950"/><button type="button" onClick={()=>{if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoPreview('');setPhotoFile(null)}} className="absolute right-2 top-2 rounded-full bg-rose-600 px-3 py-1.5 text-xs font-black text-white">Видалити</button></div>:<button type="button" onClick={()=>photoInputRef.current?.click()} className="w-full py-7 rounded-xl bg-slate-950 text-cyan-200 font-black flex flex-col items-center justify-center gap-2"><ImagePlus className="w-8 h-8"/><span>Додати фото</span><span className="text-[10px] font-medium text-slate-400">Одне фото, до 10 МБ</span></button>}<input ref={photoInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>handlePhoto(e.target.files?.[0])}/>{photoFile&&<div className="mt-2 text-[10px] text-emerald-300 font-bold flex items-center gap-1"><Camera className="w-3 h-3"/>Фото готове до завантаження</div>}</div></div>
       <div className="grid grid-cols-2 gap-2.5"><input value={payAmount} onChange={e=>setPayAmount(e.target.value)} placeholder="Ціна / оплата, грн" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/><select value={payType} onChange={e=>setPayType(e.target.value as PayType)} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"><option value="fixed">Фіксована</option><option value="hourly">За годину</option><option value="daily">За день</option><option value="monthly">За місяць</option><option value="free">Безкоштовно</option></select></div>
       <div className="grid grid-cols-2 gap-2.5"><select value={when} onChange={e=>setWhen(e.target.value)} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"><option>Сьогодні</option><option>Завтра</option><option>Найближчим часом</option><option>Постійно</option></select><input value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Тривалість" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/></div>
       {isUrgent&&<div className="p-3 rounded-2xl bg-rose-950/60 border border-rose-800/50 space-y-2"><div className="text-rose-300 text-xs font-black">🚨 ТЕРМІНОВА ДОПОМОГА</div><div className="flex flex-wrap gap-2">{(Object.keys(URGENT_TYPES_MAP) as UrgentHelpType[]).map(k=><button type="button" key={k} onClick={()=>setUrgentType(k)} className={`px-2 py-1.5 rounded-xl text-xs font-bold border ${urgentType===k?'bg-rose-600 text-white':'bg-slate-900 text-rose-200 border-rose-900'}`}>{URGENT_TYPES_MAP[k].label}</button>)}</div><div className="flex flex-wrap gap-2">{(Object.keys(URGENCY_LEVELS_MAP) as UrgencyLevel[]).map(k=><button type="button" key={k} onClick={()=>setUrgencyLevel(k)} className={`px-2 py-1.5 rounded-xl text-xs font-bold border ${urgencyLevel===k?'bg-rose-600 text-white':'bg-slate-900 text-rose-200 border-rose-900'}`}>{URGENCY_LEVELS_MAP[k].label.split('—')[0]}</button>)}</div></div>}
       <button disabled={busy||uploadingPhoto||!canPublish} type="submit" className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-purple-600 to-cyan-600 text-white font-black flex items-center justify-center gap-2 disabled:opacity-50"><Send className="w-4 h-4"/>{uploadingPhoto?'Завантаження фото...':busy?'Публікація...':'Опублікувати оголошення'}</button>
      </form>}
     </div>
    </div>
   </div>
  </div>
  <ListingMapPicker isOpen={mapOpen} initialCoordinates={coordinates} onConfirm={(coords,detectedLocation)=>{setCoordinates(coords);if(detectedLocation)setLocationName(detectedLocation);setMapOpen(false)}} onClose={()=>setMapOpen(false)}/>
 </>;
};