import React, { useEffect, useRef, useState } from 'react';
import { X, CheckCircle2, AlertCircle, Send, MapPin, LocateFixed, Loader2, Camera, ImagePlus } from 'lucide-react';
import { CategoryId, CATEGORIES, UrgencyLevel, UrgentHelpType, URGENCY_LEVELS_MAP, URGENT_TYPES_MAP, Listing, PayType } from '../types';
import { ListingMapPicker } from './ListingMapPicker';

interface CreateListingModalProps { isOpen:boolean; onClose:()=>void; onSubmit:(newListing:Omit<Listing,'id'|'createdAt'|'viewsCount'|'callsCount'|'distanceMeters'>)=>Promise<boolean>; userCoordinates?:[number,number]; gpsEnabled?:boolean; }
const MAIN_CATEGORY_IDS:CategoryId[]=['service','rideshare','sale','buy','rent','giveaway','other','urgent'];
const MAX_SOURCE_PHOTO_BYTES=10*1024*1024;
const MAX_IMAGE_SIDE=1080;
const JPEG_QUALITY=0.88;
const MAX_PHOTO_BYTES=450*1024;
const SALE_SUBCATEGORIES=CATEGORIES.sale.subcategories??[];

const compressPhotoToDataUrl=(file:File):Promise<{dataUrl:string,size:number}>=>(new Promise((resolve,reject)=>{
 const image=new Image(); const objectUrl=URL.createObjectURL(file);
 image.onload=()=>{
  try{
   const tryCompress=(side:number,quality:number)=>{
    const scale=Math.min(1,side/Math.max(image.naturalWidth,image.naturalHeight));
    const width=Math.max(1,Math.round(image.naturalWidth*scale));
    const height=Math.max(1,Math.round(image.naturalHeight*scale));
    const canvas=document.createElement('canvas'); canvas.width=width; canvas.height=height;
    const ctx=canvas.getContext('2d'); if(!ctx)throw new Error('Не вдалося підготувати фото.');
    ctx.imageSmoothingEnabled=true; ctx.imageSmoothingQuality='high';
    ctx.drawImage(image,0,0,width,height);
    canvas.toBlob(blob=>{
     if(!blob){reject(new Error('Не вдалося стиснути фото.'));return;}
     const reader=new FileReader();
     reader.onload=()=>{
      const dataUrl=String(reader.result||'');
      if(blob.size<=MAX_PHOTO_BYTES){URL.revokeObjectURL(objectUrl);resolve({dataUrl,size:blob.size});return;}
      if(quality>0.52){tryCompress(side,Math.max(0.52,quality-0.08));return;}
      if(side>720){tryCompress(Math.round(side*0.85),0.82);return;}
      if(side>540){tryCompress(Math.round(side*0.85),0.78);return;}
      URL.revokeObjectURL(objectUrl);
      reject(new Error('Фото не вдалося стиснути до безпечного розміру. Спробуйте інше фото.'));
     };
     reader.onerror=()=>{URL.revokeObjectURL(objectUrl);reject(new Error('Не вдалося прочитати стиснене фото.'));};
     reader.readAsDataURL(blob);
    },'image/jpeg',quality);
   };
   tryCompress(MAX_IMAGE_SIDE,JPEG_QUALITY);
  }catch(e){URL.revokeObjectURL(objectUrl);reject(e)}
 };
 image.onerror=()=>{URL.revokeObjectURL(objectUrl);reject(new Error('Не вдалося прочитати фото.'));}; image.src=objectUrl;
}));

export const CreateListingModal:React.FC<CreateListingModalProps>=({isOpen,onClose,onSubmit,userCoordinates,gpsEnabled=false})=>{
 const [category,setCategory]=useState<CategoryId>('service');const [subcategory,setSubcategory]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [payAmount,setPayAmount]=useState('');const [payType,setPayType]=useState<PayType>('fixed');const [locationName,setLocationName]=useState('');const [when,setWhen]=useState('Сьогодні');const [duration,setDuration]=useState('2 години');const [phone,setPhone]=useState('');const [photoUrl,setPhotoUrl]=useState('');const [photoPreview,setPhotoPreview]=useState('');const [photoOriginalSize,setPhotoOriginalSize]=useState(0);const [photoCompressedSize,setPhotoCompressedSize]=useState(0);const [mapOpen,setMapOpen]=useState(false);const [coordinates,setCoordinates]=useState<[number,number]|null>(null);const [locating,setLocating]=useState(false);const [processingPhoto,setProcessingPhoto]=useState(false);const [busy,setBusy]=useState(false);const [success,setSuccess]=useState(false);const [errorMessage,setErrorMessage]=useState('');const [urgencyLevel,setUrgencyLevel]=useState<UrgencyLevel>('immediate');const [urgentType,setUrgentType]=useState<UrgentHelpType>('auto');
 const photoInputRef=useRef<HTMLInputElement|null>(null);const cameraInputRef=useRef<HTMLInputElement|null>(null);
 const isUrgent=category==='urgent';const currentCategory=CATEGORIES[category];const subcategories=category==='sale'?SALE_SUBCATEGORIES:(currentCategory?.subcategories??[]);const selectedCoordinates=coordinates||(gpsEnabled&&userCoordinates?userCoordinates:null);const canPublish=Boolean(selectedCoordinates);
 useEffect(()=>{if(!isOpen)return;setSuccess(false);setErrorMessage('');setBusy(false);setMapOpen(false);setCoordinates(null);setPhotoUrl('');setPhotoPreview('');setPhotoOriginalSize(0);setPhotoCompressedSize(0)},[isOpen]);
 const handlePhoto=async(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){setErrorMessage('Оберіть саме фото.');return}if(file.size>MAX_SOURCE_PHOTO_BYTES){setErrorMessage('Фото завелике. Максимум 10 МБ.');return}setProcessingPhoto(true);setErrorMessage('');try{const result=await compressPhotoToDataUrl(file);setPhotoUrl(result.dataUrl);setPhotoPreview(result.dataUrl);setPhotoOriginalSize(file.size);setPhotoCompressedSize(result.size)}catch(e){setPhotoUrl('');setPhotoPreview('');setPhotoOriginalSize(0);setPhotoCompressedSize(0);setErrorMessage(e instanceof Error?e.message:'Не вдалося обробити фото.')}finally{setProcessingPhoto(false)}};
 const determineAutomatically=()=>{if(!navigator.geolocation){setErrorMessage('Цей браузер не підтримує визначення місцезнаходження.');return}setLocating(true);setErrorMessage('');navigator.geolocation.getCurrentPosition(p=>{setCoordinates([p.coords.latitude,p.coords.longitude]);setLocating(false);setMapOpen(true)},e=>{setLocating(false);setErrorMessage(e.code===1?'Дозвольте доступ до геолокації.':'Не вдалося визначити місцезнаходження. Перевірте GPS.')},{enableHighAccuracy:true,timeout:12000,maximumAge:0})};
 const clearPhoto=()=>{setPhotoUrl('');setPhotoPreview('');setPhotoOriginalSize(0);setPhotoCompressedSize(0)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy||processingPhoto)return;setErrorMessage('');if(!canPublish){setErrorMessage('📍 Спочатку визначте місце автоматично або виберіть точку на карті.');return}if(!title.trim()){setErrorMessage('Вкажіть заголовок оголошення.');return}if(!phone.trim()){setErrorMessage('Вкажіть номер телефону.');return}setBusy(true);try{let pay=payAmount?`${payAmount} грн`:'За домовленістю';if(payType==='hourly')pay+='/год';if(payType==='daily')pay+='/день';if(payType==='monthly')pay+='/міс';if(payType==='free')pay='Безкоштовно';setErrorMessage('Публікую оголошення…');const ok=await onSubmit({title:isUrgent?`🚨 ${title}`:title,category,subcategory:subcategory||undefined,description:description||'Опис не вказано.',pay,payValueNumber:parseInt(payAmount.replace(/\D/g,''),10)||0,payType,locationName:locationName.trim(),coordinates:selectedCoordinates!,when:isUrgent?'Терміново (зараз)':when,duration,phone,isUrgent,urgencyLevel:isUrgent?urgencyLevel:undefined,urgentType:isUrgent?urgentType:undefined,photoUrl:photoUrl||undefined,verified:true});if(!ok)throw new Error('Не вдалося зберегти оголошення. Перевірте Firebase.');setBusy(false);setErrorMessage('');setSuccess(true)}catch(e){console.error(e);setBusy(false);setErrorMessage(e instanceof Error?e.message:'Не вдалося опублікувати оголошення. Перевірте інтернет.')}};
 if(!isOpen)return null;
 return <><div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md overflow-y-auto overscroll-contain" style={{WebkitOverflowScrolling:'touch'}}><div className="min-h-full flex items-start justify-center p-2"><div className="relative w-full max-w-xl bg-slate-950/95 text-slate-100 rounded-3xl shadow-2xl border border-purple-900/50 my-2 flex flex-col"><div className="shrink-0 p-4 border-b border-purple-900/40 flex items-center justify-between"><div><h2 className="text-lg font-black">Додати оголошення</h2><p className="text-[11px] text-purple-300/70">Оберіть категорію та підкатегорію</p></div><button type="button" onClick={onClose} className="w-9 h-9 rounded-full bg-slate-900 text-purple-300 border border-purple-800/40 flex items-center justify-center"><X className="w-5 h-5"/></button></div>
 <div className="p-4 sm:p-6 space-y-4">{success?<div className="py-12 text-center space-y-4"><CheckCircle2 className="w-16 h-16 mx-auto text-emerald-400"/><h3 className="text-2xl font-black text-emerald-300">Оголошення додано!</h3><p className="text-sm text-slate-300">Ваше оголошення успішно опубліковано.</p><button type="button" onClick={onClose} className="px-8 py-3 bg-purple-600 rounded-2xl font-extrabold">Готово</button></div>:<form onSubmit={submit} className="space-y-4">
 <div className={`p-3 rounded-2xl border text-xs font-bold flex gap-2 ${canPublish?'bg-emerald-950/50 text-emerald-200 border-emerald-800/60':'bg-amber-950/60 text-amber-200 border-amber-800/60'}`}><MapPin className="w-4 h-4 shrink-0"/><span>{canPublish?'Місце визначено. Координати збережено.':'Визначте місце для оголошення.'}</span></div>
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><button type="button" onClick={determineAutomatically} disabled={locating} className="py-3 rounded-2xl bg-emerald-600 text-white font-black flex items-center justify-center gap-2"><LocateFixed className="w-4 h-4"/>{locating?<><Loader2 className="w-4 h-4 animate-spin"/>Визначаю...</>:'Визначити автоматично'}</button><button type="button" onClick={()=>{setErrorMessage('');setMapOpen(true)}} className="py-3 rounded-2xl bg-cyan-600 text-white font-black flex items-center justify-center gap-2"><MapPin className="w-4 h-4"/>Вказати місце на карті</button></div>
 {coordinates&&<div className="p-3 rounded-2xl bg-emerald-950/50 border border-emerald-800/50 text-xs font-bold text-emerald-200">📍 Координати вибрані: {coordinates[0].toFixed(6)}, {coordinates[1].toFixed(6)}</div>}
 {errorMessage&&<div className="p-3 bg-rose-950/80 text-rose-200 border border-rose-800/60 rounded-2xl text-xs font-bold flex gap-2"><AlertCircle className="w-4 h-4 shrink-0"/>{errorMessage}</div>}
 <div><label className="text-xs font-extrabold text-purple-300">ОСНОВНА КАТЕГОРІЯ</label><div className="flex gap-2 overflow-x-auto mt-2 pb-1">{MAIN_CATEGORY_IDS.map(k=><button key={k} type="button" onClick={()=>{setCategory(k);setSubcategory('')}} className={`shrink-0 px-3 py-2 rounded-2xl text-left border ${category===k?'bg-purple-600 text-white border-purple-400':'bg-slate-900 text-purple-200 border-purple-900/40'}`}><span>{CATEGORIES[k].pinSymbol}</span><span className="block text-xs font-extrabold mt-1">{CATEGORIES[k].shortLabel}</span></button>)}</div></div>
 {subcategories.length>0&&<div><label className="text-xs font-extrabold text-cyan-300">ПІДКАТЕГОРІЯ {category==='sale'?'— ПРОДАМ':''}</label><div className="flex flex-wrap gap-1.5 mt-2">{subcategories.map(s=><button key={s} type="button" onClick={()=>setSubcategory(subcategory===s?'':s)} className={`px-3 py-1.5 rounded-xl text-xs font-bold border ${subcategory===s?'bg-cyan-500 text-slate-950':'bg-slate-950 text-purple-200 border-purple-800/40'}`}>{s}</button>)}</div></div>}
 <input required value={title} onChange={e=>setTitle(e.target.value)} placeholder={isUrgent?'Що потрібно терміново?':'Назва оголошення'} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Опис та деталі" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/><input value={locationName} onChange={e=>setLocationName(e.target.value)} placeholder="Вулиця, номер або назва місця" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/><input value={phone} onChange={e=>setPhone(e.target.value)} required type="tel" placeholder="+380..." className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/>
 <div><label className="text-xs font-extrabold text-cyan-300">ФОТО ТОВАРУ — 1 ФОТО</label><div className="mt-2 rounded-2xl border border-dashed border-cyan-500/50 bg-slate-900/70 p-3">{photoPreview?<div className="relative"><div className="w-full max-h-[70vh] flex items-center justify-center overflow-hidden rounded-xl bg-slate-950"><img src={photoPreview} alt="Фото товару" className="block max-w-full max-h-[70vh] w-auto h-auto object-contain rounded-xl"/></div><button type="button" onClick={clearPhoto} className="absolute right-2 top-2 rounded-full bg-rose-600 px-3 py-1.5 text-xs font-black text-white">Видалити</button><div className="mt-2 text-[10px] text-emerald-300 font-bold">Стиснено: {(photoOriginalSize/1024/1024).toFixed(1)} МБ → {(photoCompressedSize/1024).toFixed(0)} КБ · збережено пропорції</div></div>:<div className="grid grid-cols-2 gap-2"><button type="button" disabled={processingPhoto} onClick={()=>cameraInputRef.current?.click()} className="py-7 rounded-xl bg-slate-950 text-cyan-200 font-black flex flex-col items-center justify-center gap-2"><Camera className="w-8 h-8"/><span>Зробити фото</span></button><button type="button" disabled={processingPhoto} onClick={()=>photoInputRef.current?.click()} className="py-7 rounded-xl bg-slate-950 text-cyan-200 font-black flex flex-col items-center justify-center gap-2"><ImagePlus className="w-8 h-8"/><span>З галереї</span></button></div>}{processingPhoto&&<div className="mt-2 text-center text-xs text-cyan-300 font-bold flex items-center justify-center gap-2"><Loader2 className="w-4 h-4 animate-spin"/>Стискаю фото…</div>}<input ref={cameraInputRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>{void handlePhoto(e.target.files?.[0]);e.currentTarget.value=''}}/><input ref={photoInputRef} type="file" accept="image/*" className="hidden" onChange={e=>{void handlePhoto(e.target.files?.[0]);e.currentTarget.value=''}}/></div></div>
 <div className="grid grid-cols-2 gap-2.5"><input value={payAmount} onChange={e=>setPayAmount(e.target.value)} placeholder="Ціна / оплата, грн" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/><select value={payType} onChange={e=>setPayType(e.target.value as PayType)} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"><option value="fixed">Фіксована</option><option value="hourly">За годину</option><option value="daily">За день</option><option value="monthly">За місяць</option><option value="free">Безкоштовно</option></select></div>
 <div className="grid grid-cols-2 gap-2.5"><select value={when} onChange={e=>setWhen(e.target.value)} className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"><option>Сьогодні</option><option>Завтра</option><option>Найближчим часом</option><option>Постійно</option></select><input value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Тривалість" className="w-full px-3.5 py-3 rounded-xl bg-slate-900 border border-purple-900/50 text-white text-sm"/></div>
 {isUrgent&&<div className="p-3 rounded-2xl bg-rose-950/60 border border-rose-800/50 space-y-2"><div className="text-rose-300 text-xs font-black">🚨 ТЕРМІНОВА ДОПОМОГА</div><div className="flex flex-wrap gap-2">{(Object.keys(URGENT_TYPES_MAP) as UrgentHelpType[]).map(k=><button type="button" key={k} onClick={()=>setUrgentType(k)} className={`px-2 py-1.5 rounded-xl text-xs font-bold border ${urgentType===k?'bg-rose-600 text-white':'bg-slate-900 text-rose-200 border-rose-900'}`}>{URGENT_TYPES_MAP[k].label}</button>)}</div><div className="flex flex-wrap gap-2">{(Object.keys(URGENCY_LEVELS_MAP) as UrgencyLevel[]).map(k=><button type="button" key={k} onClick={()=>setUrgencyLevel(k)} className={`px-2 py-1.5 rounded-xl text-xs font-bold border ${urgencyLevel===k?'bg-rose-600 text-white':'bg-slate-900 text-rose-200 border-rose-900'}`}>{URGENCY_LEVELS_MAP[k].label.split('—')[0]}</button>)}</div></div>}
 <button disabled={busy||processingPhoto||!canPublish} type="submit" className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-purple-600 to-cyan-600 text-white font-black flex items-center justify-center gap-2 disabled:opacity-50"><Send className="w-4 h-4"/>{processingPhoto?'Стискаю фото…':busy?'Публікація…':'Опублікувати оголошення'}</button>
 </form>}</div></div></div></div><ListingMapPicker isOpen={mapOpen} initialCoordinates={coordinates} onConfirm={(coords,detectedLocation)=>{setCoordinates(coords);if(detectedLocation)setLocationName(detectedLocation);setMapOpen(false)}} onClose={()=>setMapOpen(false)}/></>;
};