import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import { Layers, Crosshair, Compass, Navigation, X, Car, Footprints, ChevronRight, MapPin, Phone, ExternalLink } from 'lucide-react';
import { Listing, CATEGORIES } from '../types';
import { COMMUNITY_CENTER } from '../data/mockListings';
import { formatDistance } from '../utils/distance';
import { DistanceRangeSlider } from './DistanceRangeSlider';
import { renderMarkerHtml } from '../utils/categoryMarkerIcons';

export type MapTileStyle = 'light' | 'streets' | 'satellite' | 'dark';
interface MapViewProps { listings: Listing[]; selectedListing: Listing | null; onSelectListing: (listing: Listing | null) => void; userCoordinates?: [number, number]; setUserCoordinates?: (coords: [number, number]) => void; isPinSelectMode?: boolean; selectedPinLocation?: [number, number] | null; onPinSelected?: (coords: [number, number]) => void; activeNavigationListing?: Listing | null; onStopNavigation?: () => void; onCallListing?: (listing: Listing) => void; onRouteListing?: (listing: Listing) => void; onDetailListing?: (listing: Listing) => void; maxRadiusKm?: number | null; onChangeMaxRadiusKm?: (radius: number | null) => void; onGpsStatusChange?: (enabled: boolean) => void; }
const TILE_URLS: Record<MapTileStyle, { url: string; attr: string }> = { light:{url:'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',attr:'&copy; OpenStreetMap &copy; CARTO'}, streets:{url:'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',attr:'&copy; OpenStreetMap &copy; CARTO'}, satellite:{url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',attr:'&copy; Esri, Maxar, Earthstar Geographics'}, dark:{url:'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',attr:'&copy; OpenStreetMap &copy; CARTO'} };
export const MapView: React.FC<MapViewProps> = ({ listings, selectedListing, onSelectListing, userCoordinates, setUserCoordinates, isPinSelectMode=false, selectedPinLocation, onPinSelected, activeNavigationListing=null, onStopNavigation, onCallListing, onRouteListing, onDetailListing, maxRadiusKm=null, onChangeMaxRadiusKm, onGpsStatusChange }) => {
  const mapContainerRef=useRef<HTMLDivElement>(null), mapInstanceRef=useRef<L.Map|null>(null), tileLayerRef=useRef<L.TileLayer|null>(null), markersGroupRef=useRef<L.LayerGroup|null>(null), routeGroupRef=useRef<L.LayerGroup|null>(null), userMarkerRef=useRef<L.Marker|null>(null), radiusCircleRef=useRef<L.Circle|null>(null), pinMarkerRef=useRef<L.Marker|null>(null), onSelectRef=useRef(onSelectListing), onPinRef=useRef(onPinSelected);
  const [mapStyle,setMapStyle]=useState<MapTileStyle>('light'),[showStyleMenu,setShowStyleMenu]=useState(false),[showRadiusMenu,setShowRadiusMenu]=useState(false),[isLocating,setIsLocating]=useState(false),[gpsEnabled,setGpsEnabled]=useState(false),[realGpsCoordinates,setRealGpsCoordinates]=useState<[number,number]|null>(null),[routeError,setRouteError]=useState(false),[routeLoading,setRouteLoading]=useState(false),[navSteps,setNavSteps]=useState<string[]>([]),[currentStepIndex,setCurrentStepIndex]=useState(0);
  useEffect(()=>{onSelectRef.current=onSelectListing;onPinRef.current=onPinSelected},[onSelectListing,onPinSelected]);
  useEffect(()=>{if(!mapContainerRef.current||mapInstanceRef.current)return;const map=L.map(mapContainerRef.current,{center:COMMUNITY_CENTER,zoom:14,zoomControl:false});const tile=TILE_URLS[mapStyle];tileLayerRef.current=L.tileLayer(tile.url,{maxZoom:19,attribution:tile.attr}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);markersGroupRef.current=L.layerGroup().addTo(map);routeGroupRef.current=L.layerGroup().addTo(map);mapInstanceRef.current=map;map.on('click',e=>{if(isPinSelectMode&&onPinRef.current)onPinRef.current([e.latlng.lat,e.latlng.lng]);else onSelectRef.current(null)});setTimeout(()=>map.invalidateSize(),300);return()=>{map.remove();mapInstanceRef.current=null;tileLayerRef.current=null;markersGroupRef.current=null;routeGroupRef.current=null}},[]);
  useEffect(()=>{const map=mapInstanceRef.current;if(!map)return;tileLayerRef.current?.remove();const tile=TILE_URLS[mapStyle];tileLayerRef.current=L.tileLayer(tile.url,{maxZoom:19,attribution:tile.attr}).addTo(map)},[mapStyle]);
  const requestGPS=()=>{if(!navigator.geolocation){setGpsEnabled(false);onGpsStatusChange?.(false);return}setIsLocating(true);navigator.geolocation.getCurrentPosition(p=>{const c:[number,number]=[p.coords.latitude,p.coords.longitude];setRealGpsCoordinates(c);setGpsEnabled(true);onGpsStatusChange?.(true);setUserCoordinates?.(c);mapInstanceRef.current?.flyTo(c,16,{animate:true,duration:1.5});setIsLocating(false)},()=>{setIsLocating(false);setGpsEnabled(false);onGpsStatusChange?.(false);setRealGpsCoordinates(null)}, {enableHighAccuracy:true,timeout:15000,maximumAge:0})};
  useEffect(()=>{onGpsStatusChange?.(false)},[onGpsStatusChange]);
  useEffect(()=>{const map=mapInstanceRef.current;if(!map)return;userMarkerRef.current?.remove();radiusCircleRef.current?.remove();userMarkerRef.current=null;radiusCircleRef.current=null;if(!gpsEnabled||!realGpsCoordinates)return;const icon=L.divIcon({className:'user-location-marker',iconSize:[52,52],iconAnchor:[26,26],html:'<div style="width:52px;height:52px;border-radius:50%;background:rgba(6,182,212,.2);display:flex;align-items:center;justify-content:center"><div style="width:20px;height:20px;border-radius:50%;background:#06b6d4;border:3px solid white"></div></div>'});userMarkerRef.current=L.marker(realGpsCoordinates,{icon,zIndexOffset:2000,interactive:false}).addTo(map);if(maxRadiusKm!==null&&maxRadiusKm>0)radiusCircleRef.current=L.circle(realGpsCoordinates,{radius:maxRadiusKm*1000,color:'#c084fc',fillColor:'#a855f7',fillOpacity:.12,weight:2,dashArray:'6, 8',interactive:false}).addTo(map)},[gpsEnabled,realGpsCoordinates,maxRadiusKm]);
  useEffect(()=>{const map=mapInstanceRef.current;if(!map)return;if(isPinSelectMode&&selectedPinLocation){const icon=L.divIcon({className:'custom-pin-select-marker',iconSize:[0,0],iconAnchor:[0,0],html:'<div style="transform:translate(-50%,-100%);display:flex;flex-direction:column;align-items:center"><div style="background:#9333ea;color:white;font-weight:800;font-size:12px;padding:6px 10px;border-radius:999px;border:2px solid #c084fc;white-space:nowrap">📍 Обрана точка</div><div style="width:12px;height:12px;background:#9333ea;transform:rotate(45deg);margin-top:-5px"></div></div>'});if(pinMarkerRef.current)pinMarkerRef.current.setLatLng(selectedPinLocation);else pinMarkerRef.current=L.marker(selectedPinLocation,{icon,interactive:false}).addTo(map)}else{pinMarkerRef.current?.remove();pinMarkerRef.current=null}},[isPinSelectMode,selectedPinLocation]);
  useEffect(()=>{const map=mapInstanceRef.current,layer=markersGroupRef.current;if(!map||!layer)return;layer.clearLayers();listings.forEach(listing=>{if(!listing?.coordinates||listing.coordinates.length<2)return;const icon=L.divIcon({className:'custom-listing-marker',html:renderMarkerHtml(listing,selectedListing?.id===listing.id,activeNavigationListing?.id===listing.id),iconSize:[0,0]});const marker=L.marker(listing.coordinates,{icon}).addTo(layer);marker.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);onSelectRef.current(listing);map.panTo(listing.coordinates,{animate:true})})})},[listings,selectedListing,activeNavigationListing]);
  const handleGPSButton=()=>{if(gpsEnabled){setGpsEnabled(false);setRealGpsCoordinates(null)}else requestGPS()};
  const handleRecenter=()=>{if(gpsEnabled&&realGpsCoordinates)mapInstanceRef.current?.flyTo(realGpsCoordinates,16,{animate:true});else mapInstanceRef.current?.flyTo(COMMUNITY_CENTER,14,{animate:true})};
  return <div className="relative w-full h-full min-h-[420px] flex-1"><div ref={mapContainerRef} className="w-full h-full rounded-2xl overflow-hidden shadow-inner border border-purple-900/30"/>{isPinSelectMode&&<div className="absolute top-3 left-1/2 -translate-x-1/2 z-40 bg-purple-900/95 text-white text-xs font-bold px-4 py-2 rounded-full shadow-lg border border-purple-400/50">📍 Натисніть на карту, щоб вибрати точку</div>}<div className="absolute top-3 left-3 z-30 flex flex-col gap-2"><button aria-label="Геолокація" title={gpsEnabled?'Вимкнути геолокацію':'Увімкнути геолокацію'} onClick={handleGPSButton} disabled={isLocating} className={`p-2.5 rounded-xl shadow-lg border ${gpsEnabled?'bg-cyan-600 text-white border-cyan-300':'bg-slate-950/90 text-cyan-300 border-cyan-800/60'}`}><Crosshair className={isLocating?'w-5 h-5 animate-spin':'w-5 h-5'}/></button><button aria-label="Радіус" title="Радіус пошуку" onClick={()=>setShowRadiusMenu(v=>!v)} className="p-2.5 rounded-xl shadow-lg border bg-slate-950/90 text-purple-200 border-purple-800/60"><Compass className="w-5 h-5"/></button>{showRadiusMenu&&<div className="w-72 sm:w-80 shadow-2xl"><DistanceRangeSlider maxRadiusKm={maxRadiusKm} onChangeMaxRadiusKm={onChangeMaxRadiusKm} filteredCount={listings.length} compact/></div>}</div><div className="absolute top-3 right-3 z-30 flex flex-col gap-2"><div className="relative"><button aria-label="Шари карти" title="Шари карти" onClick={()=>setShowStyleMenu(v=>!v)} className="p-2.5 rounded-xl bg-slate-950/90 text-purple-200 border border-purple-800/50 shadow-lg"><Layers className="w-5 h-5"/></button>{showStyleMenu&&<div className="absolute right-0 top-12 bg-slate-950/95 border border-purple-800/60 rounded-2xl p-2 shadow-2xl w-48 z-40 text-xs font-extrabold">{(['light','streets','satellite','dark'] as MapTileStyle[]).map(style=><button key={style} onClick={()=>{setMapStyle(style);setShowStyleMenu(false)}} className={`w-full text-left p-2 rounded-xl ${mapStyle===style?'bg-purple-600 text-white':'text-purple-200'}`}>{style==='light'?'☀️ Світла карта':style==='streets'?'🗺️ Вулиці':style==='satellite'?'🛰️ Супутник':'🌌 Нічна карта'}{mapStyle===style&&' ✓'}</button>)}</div>}</div><button aria-label="Центр карти" title="Центр карти" onClick={handleRecenter} className="p-2.5 rounded-xl bg-slate-950/90 text-purple-200 border border-purple-800/50 shadow-lg"><Compass className="w-5 h-5"/></button></div>{!activeNavigationListing&&<div className="absolute bottom-3 left-3 z-20 bg-slate-950/85 backdrop-blur-md px-3 py-1.5 rounded-xl shadow-md border border-purple-800/50 text-[11px] font-bold text-purple-200"><span className="w-2 h-2 rounded-full bg-emerald-400 inline-block mr-2"/>Рокитне • онлайн-карта</div>}</div>;
};
