export type CategoryId =
  | 'urgent' | 'rideshare' | 'service' | 'sale' | 'buy' | 'rent' | 'giveaway' | 'other'
  | 'sale_goods' | 'sale_auto_build' | 'part_time' | 'full_time' | 'internet' | 'machinery' | 'seasonal' | 'help';
export type RideRole = 'passenger' | 'driver';
export type ServiceStatusType = 'urgent' | 'hourly' | 'daily' | 'permanent' | 'delivery' | 'seasonal';
export interface ServiceStatusInfo { id: ServiceStatusType; label: string; shortLabel: string; symbol: string; colorClass: string; borderClass: string; bgClass: string; markerBadge: string; }
export const SERVICE_STATUSES: Record<ServiceStatusType, ServiceStatusInfo> = {
  urgent:{id:'urgent',label:'ТЕРМІНОВО — потрібна допомога зараз',shortLabel:'Терміново',symbol:'🔴',colorClass:'text-red-500',borderClass:'border-red-500',bgClass:'bg-red-500/20 text-red-300 border-red-500/40',markerBadge:'🔴 ТЕРМІНОВО'},
  hourly:{id:'hourly',label:'НА ЧАС — на кілька годин',shortLabel:'На час',symbol:'🟠',colorClass:'text-orange-500',borderClass:'border-orange-500',bgClass:'bg-orange-500/20 text-orange-300 border-orange-500/40',markerBadge:'🟠 НА ЧАС'},
  daily:{id:'daily',label:'ОДНОДЕННА — робота на один день',shortLabel:'Одноденна',symbol:'🟡',colorClass:'text-yellow-500',borderClass:'border-yellow-500',bgClass:'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',markerBadge:'🟡 ОДНОДЕННА'},
  permanent:{id:'permanent',label:'ПОСТІЙНА — регулярна послуга',shortLabel:'Постійна',symbol:'🟢',colorClass:'text-emerald-500',borderClass:'border-emerald-500',bgClass:'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',markerBadge:'🟢 ПОСТІЙНА'},
  delivery:{id:'delivery',label:'ДОСТАВКА — привезти/забрати',shortLabel:'Доставка',symbol:'🔵',colorClass:'text-blue-500',borderClass:'border-blue-500',bgClass:'bg-blue-500/20 text-blue-300 border-blue-500/40',markerBadge:'🔵 ДОСТАВКА'},
  seasonal:{id:'seasonal',label:'СЕЗОННА — роботи, пов’язані з сезоном',shortLabel:'Сезонна',symbol:'🟣',colorClass:'text-purple-500',borderClass:'border-purple-500',bgClass:'bg-purple-500/20 text-purple-300 border-purple-500/40',markerBadge:'🟣 СЕЗОННА'},
};
export type UrgencyLevel = 'immediate' | 'hours' | 'today';
export type UrgentHelpType = 'medical' | 'auto' | 'physical' | 'equipment' | 'other';
export type PayType = 'fixed' | 'hourly' | 'daily' | 'monthly' | 'free';
export interface ListingComment { id:string; authorName:string; text:string; createdAt:string; rating?:number; verifiedUser?:boolean; }
export interface Listing {
  id:string; authorId?:string; authorName?:string; title:string; category:CategoryId; subcategory?:string; statusType?:ServiceStatusType; performerName?:string; rating?:number; availabilityStatus?:'available'|'busy'; serviceCategoryGroup?:string;
  description:string; pay:string; payValueNumber:number; payType:PayType; locationName:string; coordinates:[number,number]; destinationCoordinates?:[number,number]; distanceMeters:number; when:string; duration:string; phone:string; createdAt:string; isUrgent:boolean; urgencyLevel?:UrgencyLevel; urgentType?:UrgentHelpType; photoUrl?:string; verified:boolean; viewsCount:number; callsCount:number;
  rideRole?:RideRole; rideRouteFrom?:string; rideRouteTo?:string; rideDepartureTime?:string; rideSeats?:number; rideCarInfo?:string; comments?:ListingComment[];
}
export interface CategoryInfo { id:CategoryId; label:string; shortLabel:string; color:string; bgColor:string; borderColor:string; textColor:string; badgeBg:string; markerColor:string; iconName:string; pinSymbol:string; subcategories?:string[]; }

const base = (id:CategoryId,label:string,shortLabel:string,color:string,bgColor:string,borderColor:string,textColor:string,badgeBg:string,markerColor:string,iconName:string,pinSymbol:string,subcategories:string[]):CategoryInfo => ({id,label,shortLabel,color,bgColor,borderColor,textColor,badgeBg,markerColor,iconName,pinSymbol,subcategories});

export const CATEGORIES: Record<CategoryId, CategoryInfo> = {
  urgent:base('urgent','Термінова допомога','Терміново','#ef4444','bg-red-500','border-red-500','text-red-600','bg-red-50 text-red-700 border-red-200','#ef4444','Siren','🔴',['Автомобільна допомога','Медична / Ліки','Побут / Аварії','Електрика / Генератор','Втрачені речі / Тварини']),
  rideshare:base('rideshare','Підвіз','Підвіз 🚗','#0284c7','bg-sky-600','border-sky-500','text-sky-600','bg-sky-50 text-sky-700 border-sky-200','#0284c7','Car','🚗',['Водій (Пропоную поїздку)','Пасажир (Шукаю підвіз)','Міжміські поїздки','Вантажний підвіз / Посилки']),
  service:base('service','Послуги та робота','Послуги та робота','#3b82f6','bg-blue-500','border-blue-500','text-blue-600','bg-blue-50 text-blue-700 border-blue-200','#3b82f6','Wrench','🔧',['Будівництво та ремонт','Електрика','Сантехніка','Столярні роботи','Малярні роботи','Прибирання','Сад та город','Сільське господарство','Автосервіс','Комп’ютери та телефони','Краса та догляд','Догляд за дітьми','Догляд за людьми','Догляд за тваринами','Вантажні роботи','Допомога','Робота','Інші послуги']),
  sale:base('sale','Продам','Продам 🛒','#10b981','bg-emerald-600','border-emerald-500','text-emerald-600','bg-emerald-50 text-emerald-700 border-emerald-200','#10b981','ShoppingBag','🛒',['Телефони та електроніка','Нерухомість','Автомобілі','Запчастини','Для дому','Інструменти','Одяг та взуття','Дитячі товари','Сад та город','Тварини','Сільське господарство','Продукти харчування','Інше']),
  buy:base('buy','Куплю','Куплю 🔎','#f59e0b','bg-amber-600','border-amber-500','text-amber-600','bg-amber-50 text-amber-700 border-amber-200','#f59e0b','Search','🔎',['Телефони та електроніка','Нерухомість','Автомобілі','Запчастини','Для дому','Інструменти','Одяг та взуття','Дитячі товари','Сад та город','Тварини','Сільське господарство','Продукти харчування','Інше']),
  rent:base('rent','Оренда','Оренда 🏠','#8b5cf6','bg-violet-600','border-violet-500','text-violet-600','bg-violet-50 text-violet-700 border-violet-200','#8b5cf6','Home','🏠',['Квартири','Будинки','Приміщення','Автомобілі','Інструменти','Техніка','Обладнання','Інше']),
  giveaway:base('giveaway','Віддам безкоштовно','Віддам 🎁','#ec4899','bg-pink-600','border-pink-500','text-pink-600','bg-pink-50 text-pink-700 border-pink-200','#ec4899','Gift','🎁',['Одяг','Меблі','Техніка','Дитячі речі','Рослини','Тварини','Різне']),
  other:base('other','Інше','Інше 📢','#64748b','bg-slate-600','border-slate-500','text-slate-500','bg-slate-50 text-slate-700 border-slate-200','#64748b','MoreHorizontal','📢',['Оголошення','Повідомлення','Пошук','Інше']),
  sale_goods:base('sale_goods','Товари, Продукти, Побут','Товари','#10b981','bg-emerald-600','border-emerald-500','text-emerald-600','bg-emerald-50 text-emerald-700 border-emerald-200','#10b981','ShoppingBag','🛍️',['Продукти харчування / Сільгосппродукція','Побутова техніка та Меблі','Одяг, Взуття та Дитячі речі','Дрова, Опалення та Госптовари']),
  sale_auto_build:base('sale_auto_build','Авто, Будматеріали, Запчастини','Авто / Буд','#f59e0b','bg-amber-600','border-amber-500','text-amber-600','bg-amber-50 text-amber-700 border-amber-200','#f59e0b','Hammer','🧱',['Будматеріали та Інструменти','Автозапчастини та Шини','Сільгосптехніка та Запчастини','Електроніка та Обладнання']),
  part_time:base('part_time','Підробіток','Підробіток','#f97316','bg-orange-500','border-orange-500','text-orange-600','bg-orange-50 text-orange-700 border-orange-200','#f97316','Briefcase','🟠',['Вантажні роботи','Прибирання території / Сад','Ремонтні роботи','Догляд / Допомога','Підсобний робітник']),
  full_time:base('full_time','Постійна робота','Постійна робота','#10b981','bg-emerald-500','border-emerald-500','text-emerald-600','bg-emerald-50 text-emerald-700 border-emerald-200','#10b981','Building2','🟢',['Торгівля та Продавці','Водії та Логістика','Будівельні спеціальності','Сільське та Лісове господарство','Офіс та Каса']),
  internet:base('internet',"Інтернет та Зв'язок",'Інтернет','#06b6d4','bg-cyan-500','border-cyan-500','text-cyan-600','bg-cyan-50 text-cyan-700 border-cyan-200','#06b6d4','Wifi','🌐',['Starlink','Оптоволокно','Wi-Fi та Роутери','Ремонт кабелю']),
  machinery:base('machinery','Техніка та Спецтехніка','Техніка','#a855f7','bg-purple-500','border-purple-500','text-purple-600','bg-purple-50 text-purple-700 border-purple-200','#a855f7','Tractor','🟣',['Трактори та Сільгосптехніка','Оренда спецтехніки','Генератори та Електростанції','Мотоблоки та Садова техніка']),
  seasonal:base('seasonal','Сезонна робота','Сезонна','#eab308','bg-amber-500','border-amber-500','text-amber-600','bg-amber-50 text-amber-700 border-amber-200','#eab308','Sun','🟡',['Збір врожаю / Ягоди / Гриби','Заготівля дров','Сільгоспроботи (весна/осінь)','Снігоочищення']),
  help:base('help','Допомога','Допомога','#6366f1','bg-indigo-500','border-indigo-500','text-indigo-600','bg-indigo-50 text-indigo-700 border-indigo-200','#6366f1','HeartHandshake','🤝',['Гуманітарна допомога','Волонтерські збори','Втрачені речі','Пошук тварин']),
};
export const URGENT_TYPES_MAP: Record<UrgentHelpType,{label:string;icon:string;example:string}> = { medical:{label:'Потрібен лікар / медична допомога',icon:'Stethoscope',example:'Потрібно привезти ліки або виміряти тиск'}, auto:{label:'Зламалося авто / потрібен буксир',icon:'Car',example:'Грузнув у снігу або заглох двигун'}, physical:{label:'Негайна фізична допомога',icon:'ShieldAlert',example:'Потрібно підняти важке або розібрати завал'}, equipment:{label:'Інструменти / Генератор',icon:'Zap',example:'Терміново потрібен генератор / зварювальний апарат'}, other:{label:'Інша термінова допомога',icon:'AlertCircle',example:'Невідкладна ситуація в громаді'} };
export const URGENCY_LEVELS_MAP: Record<UrgencyLevel,{label:string;subtext:string;badgeClass:string}> = { immediate:{label:'Вкрай терміново — зараз!',subtext:'Потрібно протягом 15-30 хвилин',badgeClass:'bg-red-600 text-white animate-pulse'}, hours:{label:'Протягом 1-2 годин',subtext:'Потрібно якнайшвидше сьогодні',badgeClass:'bg-red-500 text-white'}, today:{label:'Сьогодні до кінця дня',subtext:'Терміново протягом дня',badgeClass:'bg-red-100 text-red-700 border border-red-300'} };
export type ActiveTab = 'map' | 'search' | 'near' | 'add' | 'more';
export type SortOption = 'distance' | 'pay' | 'newest' | 'urgent';
